name: Render PHP to HTML and Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Copy non-PHP files
        run: |
          mkdir publish
          rsync -r --exclude='*.php' --exclude='.github/' ./* publish/

      - name: Convert PHP to HTML
        run: |
          for file in $(find . -name "*.php"); do
            php $file > publish/$(basename $file .php).html
          done

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./publish
