name: Render PHP and Publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
      
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Copy non-PHP files
        run: |
          mkdir publish
          rsync -r --exclude='*.php' --exclude='.github/' ./* publish/

      - name: Convert PHP to HTML
        run: |
          for file in $(find . -name "*.php"); do
          php $file > publish/$(basename $file .php).html
          done
          find publish -type f -exec sed -i 's/\.php/\.html/g' {} \;

      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./publish
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: 'publish/'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
